def promjenaKategorije(category):
    category = category.lower()
    mapping = {
        'cestovna rasvjeta': 'Led rasvjeta',
        'cestovni i parkovski stubovi': 'Led rasvjeta',
        'led setovi': 'led set',
        'dodaci za led traku': 'Led rasvjeta',
        'hobi rasvjeta': 'Led rasvjeta',
        'gaming setovi': 'Tastatura/Miš set',
        'pohrana podataka': 'usb',
        'hladnjaci za laptope i kućišta': 'cooleri',
        'ups i prenaponska zaštita': 'Ups',
        'smart video nadzor': 'Smart sistemi',
        'smart utičnice i kabeli': 'Smart sistemi',
        'smart senzori i alarmi': 'Smart sistemi',
        'smart prekidači i dimmeri': 'Smart sistemi',
        'smart wireless ir hub': 'Smart sistemi',
        'kućni uređaji': 'ovlaživač zraka',
        'power bank i baterije': 'power bank',
        'smart satovi': 'Smartwatch',
        'konektori': 'kablovi i konektori muzička oprema',
        'ventilatori': 'ventilator za dom',
        'wi-fi produživači signala': 'EXTENDERI',
        'elektro materijal i pribor': 'Ostali materijali i oprema',
        'izolir trake': 'selotejp i trake',
        'montažni pribor': 'Ostali materijali i oprema',
        'produžni kabeli, utičnice i motalice': 'Produžni kabeli',
        'skalpeli': 'skalpeli i oprema',
        'grijanje & hlađenje': 'Klima uređaji',
        'dizalice topline': 'Toplotne pumpe',
        'dodatna oprema': 'Dijelovi za klima uređaje',
        'električni uljni radijatori': 'Električne grijalice',
        'grijalice i konvektori': 'Električne grijalice',
        'inverter klime': 'Klima uređaji',
        'kalorifer grijalice': 'Električne grijalice',
        'klima uređaji i oprema': 'Klima uređaji',
        'konvektorske grijalice': 'Električne grijalice',
        'kupaonske grijalice': 'Električne grijalice',
        'multi split klime': 'Klima uređaji',
        'panelne grijalice': 'Električne grijalice',
        'samostojeći / stubni ventilatori': 'ventilatori',
        'stolni ventilatori': 'ventilatori',
        'stropni ventilatori': 'ventilatori',
        'tretiranje zraka': 'osvježivači zraka',
        'it & gaming': 'oprema za gamere',
        'acces point & wifi reapeater': 'Access point',
        'audio & video': 'Zvučnici',
        'audio/video kabeli': 'PC kablovi',
        'bluetooth mikrofoni': 'Profesionalni mikrofoni',
        'držači i nosači': 'Nosači/držači za mobitele',
        'gadgeti': 'Bluetooth uređaji',
        'hladnjaci za laptope': 'cooleri',
        'interaktivni dječji gadgeti': 'Ostale igračke',
        'kabeli, adapteri i konektori': 'PC kablovi',
        'mediji': 'Optički mediji/diskovi',
        'mesh wi-fi system': 'router',
        'mikro glazbeni sustavi': 'Muzičke linije',
        'mobilna oprema': 'mobiteli',
        'office setovi': 'Kancelarijski materijal i oprema',
        'selfie stalci': 'Nosači/držači za mobitele',
        'tower zvučnički sustavi': 'zvučnici',
        'industrijska i tehnička rasvjeta': 'Led rasvjeta',
        'kupaonske lampe i ventilatori': 'Led rasvjeta',
        'magnetna šinska rasvjeta mystyle': 'Led rasvjeta',
        'napajanja, senzori i kontroleri': 'Led rasvjeta',
        'panik rasvjeta i piktogrami': 'Led rasvjeta',
        'unutarnja rasvjeta': 'Led rasvjeta',
        'adapteri, konektori i kabeli': 'adapteri',
        'led nakit dekorativni': 'led rasvjeta',
        'marvo': 'oprema za gamere',
        'tenda': 'oprema za gamere',
        'smart utičnice, prekidači i kabeli': 'smart utičnice',
        'cestovni i parkovski stubovi': 'Led rasvjeta',
        'led setovi': 'led set',
        'dodaci za led traku': 'Led rasvjeta',
        'hobi rasvjeta': 'Led rasvjeta',
        'gaming setovi': 'Tastatura/Miš set',
        'pohrana podataka': 'usb',
        'hladnjaci za laptope i kućišta': 'cooleri',
        'ups i prenaponska zaštita': 'Ups',
        'smart video nadzor': 'Smart sistemi',
        'smart utičnice i kabeli': 'Smart sistemi',
        'smart senzori i alarmi': 'Smart sistemi',
        'smart prekidači i dimmeri': 'Smart sistemi',
        'smart wireless ir hub': 'Smart sistemi',
        'kućni uređaji': 'ovlaživač zraka',
        'power bank i baterije': 'power bank',
        'smart satovi': 'Smartwatch',
        'konektori': 'kablovi i konektori muzička oprema',
        'ventilatori': 'ventilator za dom',
        'wi-fi produživači signala': 'EXTENDERI',
        'elektro materijal i pribor': 'Ostali materijali i oprema',
        'izolir trake': 'selotejp i trake',
        'montažni pribor': 'Ostali materijali i oprema',
        'produžni kabeli, utičnice i motalice': 'Produžni kabeli',
        'skalpeli': 'skalpeli i oprema',
        'grijanje & hlađenje': 'Klima uređaji',
        'dizalice topline': 'Toplotne pumpe',
        'dodatna oprema': 'Dijelovi za klima uređaje',
        'električni uljni radijatori': 'Električne grijalice',
        'grijalice i konvektori': 'Električne grijalice',
        'inverter klime': 'Klima uređaji',
        'kalorifer grijalice': 'Električne grijalice',
        'klima uređaji i oprema': 'Klima uređaji',
        'konvektorske grijalice': 'Električne grijalice',
        'kupaonske grijalice': 'Električne grijalice',
        'multi split klime': 'Klima uređaji',
        'panelne grijalice': 'Električne grijalice',
        'samostojeći / stubni ventilatori': 'ventilatori',
        'stolni ventilatori': 'ventilatori',
        'stropni ventilatori': 'ventilatori',
        'tretiranje zraka': 'osvježivači zraka',
        'it & gaming': 'oprema za gamere',
        'acces point & wifi reapeater': 'Access point',
        'audio & video': 'Zvučnici',
        'audio/video kabeli': 'PC kablovi',
        'bluetooth mikrofoni': 'Profesionalni mikrofoni',
        'držači i nosači': 'Nosači/držači za mobitele',
        'gadgeti': 'Bluetooth uređaji',
        'hladnjaci za laptope': 'cooleri',
        'interaktivni dječji gadgeti': 'Ostale igračke',
        'kabeli, adapteri i konektori': 'PC kablovi',
        'mediji': 'Optički mediji/diskovi',
        'mesh wi-fi system': 'router',
        'mikro glazbeni sustavi': 'Muzičke linije',
        'mobilna oprema': 'mobiteli',
        'office setovi': 'Kancelarijski materijal i oprema',
        'selfie stalci': 'Nosači/držači za mobitele',
        'tower zvučnički sustavi': 'zvučnici',
        'industrijska i tehnička rasvjeta': 'Led rasvjeta',
        'kupaonske lampe i ventilatori': 'Led rasvjeta',
        'magnetna šinska rasvjeta mystyle': 'Led rasvjeta',
        'napajanja, senzori i kontroleri': 'Led rasvjeta',
        'panik rasvjeta i piktogrami': 'Led rasvjeta',
        'unutarnja rasvjeta': 'Led rasvjeta',
        'adapteri, konektori i kabeli': 'adapteri',
        'led nakit dekorativni': 'led rasvjeta',
        'marvo': 'oprema za gamere',
        'tenda': 'oprema za gamere',
        'smart utičnice, prekidači i kabeli': 'smart utičnice'
            }
    return mapping.get(category, category)
